SoftwareEngineering/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('new_app/', include('newApp.urls', namespace='new_app')),
]

newApp/urls.py
from django.urls import path
from .views import *

app_name = 'newApp'

urlpatterns = [
    path('student/create', StudentsCreateView.as_view(), name='create_student'),
    path('student/list', StudentsListView.as_view(), name='students_list'),
    path('university/create', UniversityCreateView.as_view(), name='create_university'),
    path('university/list', UniversityListView.as_view(), name='universities_list')
]

newApp/models.py
from django.db import models
from django.urls import reverse


class University(models.Model):
    name = models.CharField(max_length=40)
    location = models.CharField(max_length=40)

    def __str__(self):
        return f"{self.name}"


class Student(models.Model):
    university = models.ForeignKey(University, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    identification_code = models.CharField(max_length=8)

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

newApp/forms.py
from django import forms
from .models import *


class UniversityModelForm(forms.ModelForm):
    class Meta:
        model = University
        fields = [
            'name',
            'location'
        ]


class StudentModelForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(StudentModelForm, self).__init__(*args, **kwargs)
        self.fields['university'].widget.attrs.update({'class': 'browser-default'})

    class Meta:
        model = Student
        fields = [
            'university',
            'first_name',
            'last_name',
            'identification_code'
        ]

SoftwareEngineering/views.py
from django.shortcuts import render


def index(request):
    if request.method == 'GET':
        context = {}
        return render(request, 'newApp/index.html', context=context)

newApp/views.py
from django.http import HttpResponse
from django.shortcuts import render
from django.views.generic import ListView, CreateView
from .models import University, Student
from .forms import UniversityModelForm, StudentModelForm


# Create your views here.

class UniversityCreateView(CreateView):
    queryset = University.objects.all()
    form_class = UniversityModelForm
    template_name = "newApp/university_create.html"
    success_url = '/new_app/university/list'


class UniversityListView(ListView):
    queryset = University.objects.all()
    template_name = "newApp/university_list.html"


class StudentsCreateView(CreateView):
    queryset = Student.objects.all()
    form_class = StudentModelForm
    template_name = "newApp/student_create.html"
    success_url = '/new_app/student/list'


class StudentsListView(ListView):
    queryset = Student.objects.all()
    template_name = "newApp/student_list.html"

templates/newApp/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Software Engineering</title>
    <link type="text/css" rel="stylesheet" href="{% static "css/materialize.min.css" %}" media="screen,projection"/>
</head>
<body>
    <nav class="nav-wrapper blue-grey darken-2">
        <div class="container">
            <a href="/" class="brand-logo left">Software Engineering</a>
            <ul>
                <li class="right"><a href="{% url 'newApp:students_list' %}">Students</a></li>
                <li class="right"><a href="{% url 'new_app:create_student' %}">Create Student</a></li>
                <li class="right"><a href="{% url 'newApp:universities_list' %}">Universities</a></li>
                <li class="right"><a href="{% url 'newApp:create_university' %}">Create University</a></li>
            </ul>
        </div>
    </nav>
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
<script type="text/javascript" src="{% static "js/materialize.min.js" %}"></script>
</body>
</html>

templates/newApp/index.html
{% extends "./base.html" %}


{% block content %}
    <h1>Welcome!!</h1>
{% endblock %}

templates/newApp/student_create.html
{% extends "./base.html" %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% block content %}
    <h1 class="btn z-depth-0 grey" style="margin-bottom: 60px;">Create Student</h1>
    <div class="row">
        <form class="col s12" method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" class="btn" value="Create">
        </form>
    </div>
{% endblock %}

</body>
</html>

templates/newApp/student_list.html
{% extends "./base.html" %}

{% block content %}
    <h1 class="btn z-depth-0 grey">Students</h1>
    {% for object in object_list %}
        <ul class="collection">
            <li class="collection-item grey lighten-3">"{{ object.first_name }}  {{ object.last_name }}" from "{{ object.university.name }}" with "{{ object.identification_code }}" identification code</li>
        </ul>
    {% endfor %}
{% endblock %}

templates/newApp/university_create.html
{% extends "./base.html" %}


{% block content %}
    <div class="row">
        <h1 class="btn z-depth-0 grey" style="margin-bottom: 60px;">Create University</h1>
        <form class="col s12" method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" class="btn" value="Create">
        </form>
    </div>
{% endblock %}

templates/newApp/university_list.html
{% extends "./base.html" %}

{% block content %}
    <h1 class="btn z-depth-0 grey">Universities</h1>
    {% for object in object_list %}
        <ul class="collection">
            <li class="collection-item grey lighten-3">"{{ object.name }}" located in "{{ object.location }}"</li>
        </ul>
    {% endfor %}
{% endblock %}